--DDL--
create DATABASE Clase;

use clase; 

CREATE TABLE alumno (
NIA CHAR (12) NOT NULL,
NIF CHAR (9),
NOMBRE VARCHAR (50) not NULL,
APEL1 VARCHAR (100) not NULL,
APEL2 VARCHAR (100),
CONSTRAINT pk_alumno PRIMARY KEY (NIF),
CONSTRAINT un_alu_nia UNIQUE (NIA)
);

--DML-
INSERT INTO alumnes2 (NIA, NIF, NOMBRE, APEL1, APEL2) VALUES ('nia1', '70052481M', 'saul', 'rocha', 'rodriguez');

INSERT INTO alumnes2 (NIA, NIF, NOMBRE, APEL1, APEL2) VALUES ('nia2', '70052547n', 'viro', 'gxrcía', 'limon');

-- DQL 

SELECT * FROM alumno;

SELECT DISTINCT APEL1 from alumnes2;
FROM ALUMNO;

CREATE TABLE IF NOT EXISTS tabla;
DROP TABLE IF EXISTS tabla;