--DDL--
CREATE DATABASE IF NOT EXISTS EJERCICIO;
USE EJERCICIO;
CREATE TABLE IF NOT EXISTS CLIENTE (
    IDCLIENTE INT,
    NOMBRE VARCHAR (100) NOT NULL,
    CUIDAD VARCHAR (50) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE IF NOT EXISTS ARTICULO (
    CODIGO CHAR (6),
    MODELO VARCHAR (50) NOT NULL,
    MARCA VARCHAR (50) NOT NULL,
    PRECIO DECIMAL (7,2) NOT NULL,
    CONSTRAINT PK_ARTICULO PRIMARY KEY (CODIGO),
    CONSTRAINT CHK_PRE_ART CHECK (PRECIO >=0) 
);

CREATE TABLE IF NOT EXISTS COMPRA (
     IDCLIENTE INT,
    CODIGO CHAR (6),
    UNIDADES INT NOT NULL,
    PRECIO DECIMAL (7,2) NOT NULL,
       FECHA DATETIME DEFAULT NOW(),
    CONSTRAINT PK_COMPRA PRIMARY KEY (IDCLIENTE,CODIGO,FECHA),
    CONSTRAINT FK_COM_IDC_CLI_IDC FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
    CONSTRAINT FK_COM_COD_ART_COD FOREIGN KEY (CODIGO) REFERENCES ARTICULO (CODIGO)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
    CONSTRAINT CHK_UNI_COM CHECK (UNIDADES >=0),
    CONSTRAINT CHK_PRE_COM CHECK (PRECIO >=0)

);

INSERT INTO CLIENTE VALUES
(22,'ALMUDENA FERNANDEZ HERNANDEZ','MADRID'),
(12,'SARA GARCIA LAFUENTE','MADRID'),
(19,'DANIEL GOMEZ GOMEZ','BARCELONA');

INSERT INTO ARTICULO VALUES
('A001','EOS 550D','CANNON',349.89),
('A002', 'SLIM 1.16','PARROT',78.99),
('A005','PX730','EPSON',250);

INSERT INTO COMPRA VALUES
(22,'A001',1,340,'2022-09-09 18:05:55'),
(22,'A005',2,250,'2022-09-09 18:05:55'),
(12,'A005',1,310.25,'2022-07-21 03:32:02');


INSERT INTO COMPRA VALUES
(12,'A005',1,310.25,'2022-09-09 18:05:55');

UPDATE COMPRA
SET UNIDADES = 3, PRECIO = 400, FECHA ='2023-09-10'
WHERE IDCLIENTE=12 && FECHA = '2022-09-09 18:05:55';

DELETE FROM CLIENTE WHERE IDCLIENTE=22;

ALTER TABLE COMPRA DROP CONSTRAINT FK_COM_IDC_CLI_IDC;

ALTER TABLE COMPRA ADD  CONSTRAINT FK_COM_IDC_CLI_IDC FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
    ON DELETE CASCADE
    ON UPDATE CASCADE;